import type {SeoTemplateName} from '@/modules/seo/shared/seo-schemas';

export const TEXT_SEO_TEMPLATES = [
  'json-ld',
  'robots-txt',
  'meta-pack',
  'image-workflow',
] as const satisfies readonly SeoTemplateName[];

export function buildRobotsTxt(params: Record<string, string>): string {
  const userAgent = params.userAgent || '*';
  const allow = params.allow || '/';
  const disallow = params.disallow;
  const crawlDelay = params.crawlDelay;
  const sitemap = params.sitemap;
  const aiPolicy = params.aiCrawlerPolicy || 'allow';

  const lines = [
    '# robots.txt generated by Social Card SEO Builder',
    `User-agent: ${userAgent}`,
    `Allow: ${allow}`,
    ...(disallow ? [`Disallow: ${disallow}`] : []),
    ...(crawlDelay ? [`Crawl-delay: ${crawlDelay}`] : []),
    '',
    '# AI crawlers',
    'User-agent: GPTBot',
    aiPolicy === 'disallow' ? 'Disallow: /' : 'Allow: /',
    'User-agent: Google-Extended',
    aiPolicy === 'disallow' ? 'Disallow: /' : 'Allow: /',
    'User-agent: PerplexityBot',
    aiPolicy === 'disallow' ? 'Disallow: /' : 'Allow: /',
    ...(sitemap ? ['', `Sitemap: ${sitemap}`] : []),
  ];

  return lines.join('\n');
}

export function buildMetaPackSnippet(params: Record<string, string>): string {
  const title = params.title || 'Social Card';
  const description =
    params.description ||
    'Generate OG images, badges, and SEO assets in one place.';
  const canonical = params.canonical;
  const robots = params.robots || 'index,follow,max-image-preview:large';
  const ogType = params.ogType || 'website';
  const ogImage = params.ogImage;
  const siteName = params.siteName;
  const locale = params.locale || 'en_US';
  const twitterCard = params.twitterCard || 'summary_large_image';
  const twitterSite = params.twitterSite;
  const themeColor = params.themeColor || '#0f0f0f';
  const keywords = params.keywords;

  const lines = [
    '<!-- SEO meta pack generated by Social Card -->',
    `<title>${escapeHtml(title)}</title>`,
    `<meta name="description" content="${escapeHtml(description)}" />`,
    `<meta name="robots" content="${escapeHtml(robots)}" />`,
    ...(keywords
      ? [`<meta name="keywords" content="${escapeHtml(keywords)}" />`]
      : []),
    ...(canonical ? [`<link rel="canonical" href="${canonical}" />`] : []),
    `<meta property="og:type" content="${escapeHtml(ogType)}" />`,
    `<meta property="og:title" content="${escapeHtml(title)}" />`,
    `<meta property="og:description" content="${escapeHtml(description)}" />`,
    `<meta property="og:locale" content="${escapeHtml(locale)}" />`,
    ...(siteName
      ? [`<meta property="og:site_name" content="${escapeHtml(siteName)}" />`]
      : []),
    ...(canonical ? [`<meta property="og:url" content="${canonical}" />`] : []),
    ...(ogImage ? [`<meta property="og:image" content="${ogImage}" />`] : []),
    `<meta name="twitter:card" content="${escapeHtml(twitterCard)}" />`,
    `<meta name="twitter:title" content="${escapeHtml(title)}" />`,
    `<meta name="twitter:description" content="${escapeHtml(description)}" />`,
    ...(twitterSite
      ? [`<meta name="twitter:site" content="${escapeHtml(twitterSite)}" />`]
      : []),
    ...(ogImage ? [`<meta name="twitter:image" content="${ogImage}" />`] : []),
    `<meta name="theme-color" content="${escapeHtml(themeColor)}" />`,
  ];

  return lines.join('\n');
}

function escapeHtml(input: string): string {
  return input
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;');
}
