import type {OgFontDefinition} from '@/modules/og/shared/og-font-types';
import {
  createGoogleFont,
  createLocalFont,
} from '@/modules/og/shared/og-font-types';

export const MONO_FONTS: readonly OgFontDefinition[] = [
  createGoogleFont(
    'mono',
    'JetBrains Mono',
    'JetBrains Mono',
    'mono',
    [400, 700],
    {
      ligatures: true,
      localFiles: [
        {path: 'jetbrains-mono-400.ttf', weight: 400},
        {path: 'jetbrains-mono-700.ttf', weight: 700},
      ],
    },
  ),
  createGoogleFont('fira-code', 'Fira Code', 'Fira Code', 'mono', [400, 700], {
    ligatures: true,
  }),
  createGoogleFont(
    'roboto-mono',
    'Roboto Mono',
    'Roboto Mono',
    'mono',
    [400, 700],
  ),
  createGoogleFont(
    'source-code-pro',
    'Source Code Pro',
    'Source Code Pro',
    'mono',
    [400, 700],
  ),
  createGoogleFont(
    'space-mono',
    'Space Mono',
    'Space Mono',
    'mono',
    [400, 700],
  ),
  createGoogleFont(
    'ubuntu-mono',
    'Ubuntu Mono',
    'Ubuntu Mono',
    'mono',
    [400, 700],
  ),
  createGoogleFont(
    'inconsolata',
    'Inconsolata',
    'Inconsolata',
    'mono',
    [400, 700],
  ),
  createGoogleFont('dm-mono', 'DM Mono', 'DM Mono', 'mono', [400, 500]),
  createGoogleFont(
    'azeret-mono',
    'Azeret Mono',
    'Azeret Mono',
    'mono',
    [400, 700],
  ),
  createGoogleFont(
    'overpass-mono',
    'Overpass Mono',
    'Overpass Mono',
    'mono',
    [400, 700],
  ),
  createGoogleFont(
    'share-tech-mono',
    'Share Tech Mono',
    'Share Tech Mono',
    'mono',
    [400],
  ),
  createGoogleFont(
    'chivo-mono',
    'Chivo Mono',
    'Chivo Mono',
    'mono',
    [400, 700],
  ),
  createGoogleFont(
    'courier-prime',
    'Courier Prime',
    'Courier Prime',
    'mono',
    [400, 700],
  ),
  createGoogleFont(
    'victor-mono',
    'Victor Mono',
    'Victor Mono',
    'mono',
    [400, 700],
    {ligatures: true},
  ),
  createGoogleFont(
    'cascadia-code',
    'Cascadia Code',
    'Cascadia Code',
    'mono',
    [400],
    {ligatures: true},
  ),
  createLocalFont(
    'commit-mono',
    'Commit Mono',
    'Commit Mono',
    'mono',
    [400, 700],
    [
      {path: 'commit-mono-400.otf', weight: 400},
      {path: 'commit-mono-700.otf', weight: 700},
    ],
    {ligatures: true},
  ),
  createLocalFont(
    'maple-mono',
    'Maple Mono',
    'Maple Mono',
    'mono',
    [400, 700],
    [
      {path: 'maple-mono-400.ttf', weight: 400},
      {path: 'maple-mono-700.ttf', weight: 700},
    ],
    {ligatures: true},
  ),
  createLocalFont(
    'monaspace-neon',
    'Monaspace Neon',
    'Monaspace Neon',
    'mono',
    [400, 700],
    [
      {path: 'monaspace-neon-400.otf', weight: 400},
      {path: 'monaspace-neon-700.otf', weight: 700},
    ],
    {ligatures: true},
  ),
  createLocalFont(
    'monaspace-argon',
    'Monaspace Argon',
    'Monaspace Argon',
    'mono',
    [400],
    [{path: 'monaspace-argon-400.otf', weight: 400}],
    {ligatures: true},
  ),
  createLocalFont(
    'monaspace-krypton',
    'Monaspace Krypton',
    'Monaspace Krypton',
    'mono',
    [400],
    [{path: 'monaspace-krypton-400.otf', weight: 400}],
    {ligatures: true},
  ),
  createLocalFont(
    'monaspace-xenon',
    'Monaspace Xenon',
    'Monaspace Xenon',
    'mono',
    [400, 700],
    [
      {path: 'monaspace-xenon-400.otf', weight: 400},
      {path: 'monaspace-xenon-400.otf', weight: 700},
    ],
    {ligatures: true},
  ),
  createLocalFont(
    'monaspace-radon',
    'Monaspace Radon',
    'Monaspace Radon',
    'mono',
    [400],
    [{path: 'monaspace-radon-400.otf', weight: 400}],
    {ligatures: true},
  ),
];
